### ISSUE TITLE
检查run结果出现问题

### ISSUE THREAD

**Issue by fightingzld** [YooKing/HAUT_autoCheck#12]
打开run检查结果时，出现获取depeid失败和服务器错误，麻烦请指教该如何解决，谢谢

![8)$P$)KPJ~Z5Y6ZD7_1SJ H](https://user-images.githubusercontent.com/71822512/94154826-e05b4b00-feb0-11ea-9168-27a7962f6823.png)

**Comment by YooKing** [comment]
已经修复，重新fork我的项目

**Comment by YooKing** [comment]
看看USERS信息有没有填准确,可以在 `text.json`找查一下有没有自己的班级,专科班级可能需要会多一个专字。

**Comment by YooKing** [comment]
另外刚才已经修复死循环Bug

**Comment by fightingzld** [comment]
您好，在设置完成后在运行-时钟里面有一个任务就代表了三个时间打卡吗？我这弄完之后有两个readme和一个main，最新设置的readme能用，其余两个不能用，这影响不影响
