### ISSUE TITLE
123

### ISSUE THREAD

**Issue by fightingzld** [YooKing/HAUT_autoCheck#13]
您好，在设置完成后在运行-时钟里面有一个任务就代表了三个时间打卡吗？我这弄完之后有两个readme和一个main，最新设置的readme能用，其余两个不能用，这影响不影响，麻烦了

**Comment by YooKing** [comment]
不影响，那是运行记录。定时，修改文件一些操作，都会运行并记录一次。不过你的前两个记录陷入死循环了，删掉吧
