### ISSUE TITLE
一直显示Maybe打卡失败

### ISSUE THREAD

**Issue by ghost** [YooKing/HAUT_autoCheck#14]
很好奇什么原因，serect也检查好几遍了，不知道为什么一直不成功。
![火狐截图_2020-09-25T05-36-51 226Z](https://user-images.githubusercontent.com/71834762/94230358-62408800-ff34-11ea-9398-28d70bf67e36.png)

**Comment by YooKing** [comment]
应该还是USERS没填好，看看英文逗号，顺序对不对

**Comment by fightingzld** [comment]
更新users再添加别的账号需要再把原来的账号信息输入一遍吗

**Comment by YooKing** [comment]
> 更新users再添加别的账号需要再把原来的账号信息输入一遍吗

需要

**Comment by ghost** [comment]
把serve酱的链接删掉就正常了，不知道是不是它自动换行的原因。
