### ISSUE TITLE
服务器错误是啥情况啊

### ISSUE THREAD

**Issue by 2917320323** [YooKing/HAUT_autoCheck#18]
我是嵩山路老校区的，运行的时候说名单里没有，想着可能老校区就是会没有
然后就抓包，填了一遍Secrets，再运行就报错，服务器错误了
`开始获取用户910815DeptId
获取deptId成功!
服务器错误！
Traceback (most recent call last):
  File "main.py", line 209, in <module>
    main()
  File "main.py", line 96, in main
    print(msg)
UnboundLocalError: local variable 'msg' referenced before assignment
Error: Process completed with exit code 1.`

**Comment by YooKing** [comment]
你修改了json，你仔细琢磨琢磨😂

**Comment by 2917320323** [comment]
没修改json，不过你提醒了我，在text.json里发现我专业的deptId与我填的不同，我把deptId改成这里面的71891，运行成功，提示时间不符合，打算明天中午再看看，但是还有一个问题，我是以我手机端爬出来的数据为准还是以text.json里的为准啊，手机爬出来的页面是71899，text.json里是71891`\":{\"deptid\":71899,\"text\":\"中英国际学院(软件学院)-计算机类( 专科 )-计专1908\"},\"isopen\":null,\"`

**Comment by 2917320323** [comment]
> 你修改了json，你仔细琢磨琢磨😂

懂了，感谢大佬解惑

**Comment by YooKing** [comment]
```
"text": "中英国际学院(软件学院)-计算机类(专科)-计专1908"
```
要加引号写。

**Comment by 2917320323** [comment]
🆗，我以为没报错就可以不加引号，现在就看明天11点半咋样了

**Comment by YooKing** [comment]
> 🆗，我以为没报错就可以不加引号，现在就看明天11点半咋样了

时间也设置错误了，它的定时是UTC时间，+8小时才是北京时间

**Comment by 2917320323** [comment]
那如果设置13点30开始的话就得写为30 5 * * *吗，懂了

**Comment by YooKing** [comment]
> 那如果设置13点30开始的话就得写为30 5 * * *吗，懂了

<div align=center>

| 标题| 内容 |
| :----:| :----: |
|姓名|个人姓名|
|学号|学号|
|学院-专业-班级|学院-专业-班级`探月工程学院-土豆种植-土种1901`中间要有连字符，班级一定要填准确。|
|微信推送链接|`https://sc.ftqq.com/你的SCKEY.send`(server酱)|

</div>

| Secrets| 内容 |备注|
| :----:| :----: |:----:|
|USERS|`姓名,学号,学院-专业-班级,微信推送链接`|①英文逗号<br>②多用户只需换行，按照格式再输入一行<br>③微信推送只需一个且要填在第一个用户后面。<br>④如果不填推送链接，每行末尾保留逗号。|

老哥仔细看看要求，不会报错😂

**Comment by 2917320323** [comment]
重新填了一遍USERS，又可以了，我中间也没动过，玄学，一定是玄学

**Comment by 2917320323** [comment]
大佬，运行成功了，能不能加个联系方式，交流学习一下。

**Comment by 2917320323** [comment]
> > 那如果设置13点30开始的话就得写为30 5 * * *吗，懂了
> 
> 标题	内容
> 姓名	个人姓名
> 学号	学号
> 学院-专业-班级	学院-专业-`探月工程学院-土豆种植-土种1901`班级中间要有连字符，班级一定要填准确。
> 微信推链接	`https://sc.ftqq.com/你的SCKEY.send`（服务器酱）
> 机密	内容	备注
> 用户	`姓名,学号,学院-专业-班级,微信推送链接`	①英语
> 逗号②多用户只需换行，按照格式再输入一行
> ③微信推一下一个而且要填在第一个用户后面
> 。④如果不填推送链接，每行末尾保留逗号。
> 老哥仔细看看要求，不会报错😂

大佬，运行成功了，能不能加个联系方式，交流学习一下。

**Comment by YooKing** [comment]
基hub交流就行，我算是业余的😂
