### ISSUE TITLE
已经解决完美校园服务器验证问题。

### ISSUE THREAD

**Issue by YooKing** [YooKing/HAUT_autoCheck#22]
需要完美校园手机号和密码，具体输入查看[Wiki](https://github.com/YooKing/HAUT_autoCheck/wiki) 。

**Comment by SunLRikka** [comment]
学号为2018开头的是否无法打19级的卡——来自降级转专业的同学
报错代码
`开始获取用户4431DeptId
获取deptId成功!
{
	"msg":"业务异常",
	"code":"10007",
	"data":"您的信息尚未在系统名单中，请再次核实。"
}
4431打卡失败-12:58:31`

**Comment by YooKing** [comment]
可以，可能那个deptID文件中，对应你的班级的ID有变化，你可以先自行抓包，然后在text.json里修改一下

**Comment by YooKing** [comment]
已经更新text.json 看看是否有你的班级
