### ISSUE TITLE
湖南工业大学，用手机打卡就成功，用程序就出现这个，怎么办

### ISSUE THREAD

**Issue by 2926295173** [YooKing/HAUT_autoCheck#27]
{
	"msg":"业务异常",
	"code":"10007",
	"data":"请在正确的打卡时间打卡"
}

**Comment by YooKing** [comment]
是不是就是不在正确时间😂

**Comment by 2926295173** [comment]
对的，是不是得等明天？






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yooking"<notifications@github.com&gt;; 
发送时间: 2020年11月14日(星期六) 晚上6:33
收件人: "YooKing/HAUT_autoCheck"<HAUT_autoCheck@noreply.github.com&gt;; 
抄送: "Aoian"<2926295173@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [YooKing/HAUT_autoCheck] 湖南工业大学，用手机打卡就成功，用程序就出现这个，怎么办 (#27)





 
是不是就是不在正确时间😂

**Comment by YooKing** [comment]
明天看看

**Comment by 2926295173** [comment]
好的，谢谢啦，我明天看看



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yooking"<notifications@github.com&gt;; 
发送时间: 2020年11月14日(星期六) 晚上6:36
收件人: "YooKing/HAUT_autoCheck"<HAUT_autoCheck@noreply.github.com&gt;; 
抄送: "Aoian"<2926295173@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [YooKing/HAUT_autoCheck] 湖南工业大学，用手机打卡就成功，用程序就出现这个，怎么办 (#27)





 
明天看看

**Comment by 2926295173** [comment]
不行，今天它5点给我打卡，还是1007业务异常，打卡失败怎么办啊这发自我的荣耀手机-------- 原始邮件 --------发件人： Yooking <notifications@github.com>日期： 2020年11月14日周六 18:36收件人： YooKing/HAUT_autoCheck <HAUT_autoCheck@noreply.github.com>抄送： 2926295173 <2926295173@qq.com>, Author <author@noreply.github.com>主    题： Re: [YooKing/HAUT_autoCheck] 湖南工业大学，用手机打卡就成功，用程序就出现这个，怎么办 (#27)

明天看看

**Comment by YooKing** [comment]
我这个默认打中午时间段
你可以自行抓包看看customerAppTypeRuleId 
在不同时间段设置不同的值应该可以

**Comment by 2926295173** [comment]
customerid":"786",
是这个不？

**Comment by 2926295173** [comment]
{"businessType":"epmpics","method":"submitUpInfo","jsonData":{"deptStr":{"deptid":224128,"text":"土木工程学院-土木大类-土木类2006"},"areaStr":"{\"streetNumber\":\"\",\"street\":\"崇德路\",\"district\":\"天元区\",\"city\":\"株洲市\",\"province\":\"湖南省\",\"town\":\"\",\"pois\":\"湖南工业大学新校区\",\"lng\":113.11425800000013,\"lat\":27.82441698950754,\"address\":\"天元区崇德路湖南工业大学新校区\",\"text\":\"湖南省-株洲市\",\"code\":\"\"}","reportdate":1605257492365,"customerid":"786","deptid":224128,"source":"app","templateid":"pneumonia","stuNo":"20407000609","username":"677","phonenum":"13293261470","userid":"25060376","updatainfo":[{"propertyname":"temperature","value":"36.4"},{"propertyname":"symptom","value":"无症状"},{"propertyname":"isConfirmed","value":"否"},{"propertyname":"isdefinde","value":"否.未隔离"},{"propertyname":"isGoWarningAdress","value":"否"},{"propertyname":"isTouch","value":"否"},{"propertyname":"isFFHasSymptom","value":"没有"},{"propertyname":"isContactFriendIn14","value":"没有"},{"propertyname":"xinqing","value":"健康"},{"propertyname":"bodyzk","value":"否"},{"propertyname":"cxjh","value":"否"},{"propertyname":"isleaveaddress","value":"否"},{"propertyname":"gtjz0511","value":"否"},{"propertyname":"medicalObservation","value":"绿色"},{"propertyname":"ownPhone","value":"13293261470"},{"propertyname":"emergencyContact","value":"13603344392"},{"propertyname":"mergencyPeoplePhone","value":"13603344392"},{"propertyname":"assistRemark","value":""}],"gpsType":0,"token":"fa01bb57-9979-491f-8b9b-49a9d0f0695e"}}

**Comment by 2926295173** [comment]
包中并未含customerAppTypeRuleId

**Comment by srcrs** [comment]
> 不行，今天它5点给我打卡，还是1007业务异常，打卡失败怎么办啊这发自我的荣耀手机-------- 原始邮件 --------发件人： Yooking <notifications@github.com>日期： 2020年11月14日周六 18:36收件人： YooKing/HAUT_autoCheck <HAUT_autoCheck@noreply.github.com>抄送： 2926295173 <2926295173@qq.com>, Author <author@noreply.github.com>主 题： Re: [YooKing/HAUT_autoCheck] 湖南工业大学，用手机打卡就成功，用程序就出现这个，怎么办 (#27) 明天看看 —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

每个学校的打卡参数不太一样，你是否适配过自己的学校？
