### ISSUE TITLE
打卡时间怎么越来越晚了呢？

### ISSUE THREAD

**Issue by arcsin3x** [YooKing/HAUT_autoCheck#31]
我设置的11点10分打卡，每次都是11点30多，现在越来越靠后，都11点40了才打卡，怎么回事呢？延迟好大啊，谢谢！

**Comment by YooKing** [comment]
猜是github代理池原因吧，建议自己提前一下

**Comment by arcsin3x** [comment]
> 猜是github代理池原因吧，建议自己提前一下

OK，非常感谢！
