### ISSUE TITLE
Action后run失败 报错

### ISSUE THREAD

**Issue by MakarovLee-1024** [YooKing/HAUT_autoCheck#41]
开始尝试为用户打卡
<class 'IndexError'>
Traceback (most recent call last):
  File "main.py", line 28, in main
    campus = CampusCard(phone[index], password[index])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 222, in <module>
    main()
  File "main.py", line 61, in main
    result=response
UnboundLocalError: local variable 'response' referenced before assignment
Error: Process completed with exit code 1.

**Comment by YooKing** [comment]
看看是users输入格式错了

**Comment by MakarovLee-1024** [comment]
> 看看是用户输入格式错了
在secret里面 update一个
150xxx,Password,SUCxxx
是这样吧

**Comment by MakarovLee-1024** [comment]
已解决 SUERS 我自定义了个别的……只能使用SUERS 感谢
