### ISSUE TITLE
腾讯云函数版本@Revincx

### ISSUE THREAD

**Issue by Revincx** [YooKing/HAUT_autoCheck#45]
刚刚搞出来的，调试的时候没问题，但不排除有其他bug，欢迎大家尝试。
项目地址：https://github.com/Revincx/HAUT_autoCheck_SCF

**Comment by chillsoul** [comment]
对于腾讯云函数，使用环境变量部署后似乎无法再次修改，建议内嵌。

**Comment by Revincx** [comment]
> 对于腾讯云函数，使用环境变量部署后似乎无法再次修改，建议内嵌。

可以修改的，我特地去试了一下

**Comment by chillsoul** [comment]
> > 对于腾讯云函数，使用环境变量部署后似乎无法再次修改，建议内嵌。
> 
> 可以修改的，我特地去试了一下

:sleepy:那就是我没找到入口了

**Comment by Revincx** [comment]
函数管理 - 函数配置 - 点右上角的编辑

**Comment by lifeilin0421** [comment]
> 函数管理 - 函数配置 - 点右上角的编辑

是使用Git下载代码仓库到本地的吗？

**Comment by Revincx** [comment]
> > 函数管理 - 函数配置 - 点右上角的编辑
> 
> 是使用Git下载代码仓库到本地的吗？

对，用git，直接下载会多一层文件夹

**Comment by lifeilin0421** [comment]
> > > 函数管理 - 函数配置 - 点右上角的编辑
> > 
> > 
> > 是使用Git下载代码仓库到本地的吗？
> 
> 对，用git，直接下载会多一层文件夹

好的，谢谢啦。

**Comment by tanryliu** [comment]
请教 @Revincx ，我之前用了很多方法把 Crypto和pycryptodome-3.9.9.dist-info打包入zip上传到云，虽然能找到包了，但是运行还是会报错。请问一下，你这2个文件夹是如何解决这个问题的。谢谢

**Comment by Revincx** [comment]
> 请教 @Revincx ，我之前用了很多方法把 Crypto和pycryptodome-3.9.9.dist-info打包入zip上传到云，虽然能找到包了，但是运行还是会报错。请问一下，你这2个文件夹是如何解决这个问题的。谢谢

我开始也碰到了这个问题，后来查了文档，腾讯云函数运行的环境是CentOS7与Python3.6，打包依赖必须在相同的环境下打包才能运行。

按照文档里面的步骤，用docker拉取腾讯云的镜像后再用pipreqs生成requirements.txt，然后用`pip install -r requirements.txt -t .`将依赖安装到当前目录就行了。这里注意一下，腾讯云那边已经有了urllib和requests这两个依赖，所以在requirements.txt只留下pycryptdome就可以。

**Comment by tanryliu** [comment]
> > 请教 @Revincx ，我之前用了很多方法把 Crypto和pycryptodome-3.9.9.dist-info打包入zip上传到云，虽然能找到包了，但是运行还是会报错。请问一下，你这2个文件夹是如何解决这个问题的。谢谢
> 
> 我开始也碰到了这个问题，后来查了文档，腾讯云函数运行的环境是CentOS7与Python3.6，打包依赖必须在相同的环境下打包才能运行。
> 
> 按照文档里面的步骤，用docker拉取腾讯云的镜像后再用pipreqs生成requirements.txt，然后用`pip install -r requirements.txt -t .`将依赖安装到当前目录就行了。这里注意一下，腾讯云那边已经有了urllib和requests这两个依赖，所以在requirements.txt只留下pycryptdome就可以。

明白，谢谢。

**Comment by du1370484311** [comment]
请教 @Revincx，获取上一次的打卡数据遍历的时候出现Class keyerror ，我看了一下我打卡，每次进去有两个属性值是空的，就要你自己填，这种情况怎么解决？

**Comment by Revincx** [comment]
> 请教 @Revincx，获取上一次的打卡数据遍历的时候出现Class keyerror ，我看了一下我打卡，每次进去有两个属性值是空的，就要你自己填，这种情况怎么解决？

没有碰到过这种情况，哪两项是空的？
实在不行可以改一下代码，不读取这两项，在提交函数里手动填上数据。

**Comment by vercen** [comment]
它说未找到函数入口执行文件

**Comment by Revincx** [comment]
> 它说未找到函数入口执行文件

你看看执行方法是不是index.main_handler，然后代码的路径对不对

**Comment by YooKing** [comment]
> 它说未找到函数入口执行文件

或者是直接下载的有一层文件夹，把里面的文件提到上一层

**Comment by vercen** [comment]
> > 它说未找到函数入口执行文件
> 
> 或者是直接下载的有一层文件夹，把里面的文件提到上一层

好的，谢谢，可以了。谢谢学长

**Comment by vercen** [comment]
我的没有打卡不知道为什么

**Comment by vercen** [comment]
打开了，没有通知

**Comment by YooKing** [comment]
> 打开了，没有通知

日志查询里看看

**Comment by du1370484311** [comment]
{"errorCode":-1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 95, in getUserInfo\n    return response.json()['userInfo']\nKeyError: 'userInfo'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 176, in handle\n    ret = self.real_handler(event, context)\n  File \"/var/user/index.py\", line 348, in main_handler\n    main()\n  File \"/var/user/index.py\", line 69, in main\n    result=response\nUnboundLocalError: local variable 'response' referenced before assignment","statusCode":430}
之前几天打卡都好好的，今天打卡就报这个错，看了一下是userInfo的问题，但不知道是什么问题，之前也没有出错啊。
