### ISSUE TITLE
报binascii错误，请问这个应该怎么解决呀？

### ISSUE THREAD

**Issue by 948693350** [YooKing/HAUT_autoCheck#58]
开始尝试为用户8759打卡
<class 'binascii.Error'>
8759打卡出错，开始第1次重试...
<class 'binascii.Error'>
8759打卡出错，开始第2次重试...
<class 'binascii.Error'>
8759打卡出错，开始第3次重试...
<class 'binascii.Error'>
11:00:56 8759出现错误

**Comment by YooKing** [comment]
不能用action了，部署到其他地方

**Comment by 948693350** [comment]
用腾讯的可以吗

**Comment by YooKing** [comment]
> 用腾讯的可以吗

好像也不太可以，在自己电脑和服务器上可以

**Comment by ReaJason** [comment]
> 用腾讯的可以吗

我云函数可以登录成功🙌（凑凑热闹）

**Comment by 948693350** [comment]
> > 用腾讯的可以吗
> 
> 我云函数可以登录成功🙌（凑凑热闹）

我用腾讯云函数他报错UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)，请问你之前有这个错误吗

**Comment by ReaJason** [comment]
> > > 用腾讯的可以吗
> > 
> > 
> > 我云函数可以登录成功🙌（凑凑热闹）
> 
> 我用腾讯云函数他报错UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)，请问你之前有这个错误吗

没有出现过

**Comment by 948693350** [comment]
> > > > 用腾讯的可以吗
> > > 
> > > 
> > > 我云函数可以登录成功🙌（凑凑热闹）
> > 
> > 
> > 我用腾讯云函数他报错UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)，请问你之前有这个错误吗
> 
> 没有出现过

可以给我一份你腾讯云的代码包吗，感激不尽

**Comment by 948693350** [comment]
> > > > > 用腾讯的可以吗
> > > > 
> > > > 
> > > > 我云函数可以登录成功🙌（凑凑热闹）
> > > 
> > > 
> > > 我用腾讯云函数他报错UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)，请问你之前有这个错误吗
> > 
> > 
> > 没有出现过
> 
> 可以给我一份你腾讯云的代码包吗，感激不尽

我看到你的空间了，我先试试，有问题再问你，多谢啦~

**Comment by zhazhalaila** [comment]
编码问题吧，在main.py第一行写入下面代码
```
# coding: utf8
```
