### ISSUE TITLE
感谢帮助，这是在校打卡的抓包内容。

### ISSUE THREAD

**Issue by vercen** [YooKing/HAUT_autoCheck#6]
![qq_pic_merged_1599571443550](https://user-images.githubusercontent.com/70558042/92482112-d3d0c480-f219-11ea-86f3-ef04755eae8b.jpg)
![qq_pic_merged_1599571470588](https://user-images.githubusercontent.com/70558042/92482120-d59a8800-f219-11ea-956c-662d0e30b6cb.jpg)
![Screenshot_2020-09-08-21-20-12-016_com guoshi htt](https://user-images.githubusercontent.com/70558042/92482124-d6cbb500-f219-11ea-84dd-ad0bca75b69b.jpg)

**Comment by YooKing** [comment]
这些内容可以贴到提交json里，如法炮制，隐私信息用secret，signurl如果有变动就改一下，最后把workflow改成一天三个时间就行。
