### ISSUE TITLE
定时打卡失败

### ISSUE THREAD

**Issue by lbhzy** [YooKing/HAUT_autoCheck#9]
![image](https://user-images.githubusercontent.com/48149261/93161467-34459180-f745-11ea-960f-d99ae0c4f703.png)

我的workflows里定时是这样的

```
schedule:
    - cron: 30,0 4,13,22 * * * 
```
打卡的时间对上了6点和6点半，但是没有打卡成功

补充：中午打卡成功了

**Comment by YooKing** [comment]
之前更新已经解决了。
```
#早中午判断
nowTime = (time.localtime().tm_hour + 8) % 24

**Comment by lbhzy** [comment]
> 之前更新已经解决了。
> 
> ```
> #早中午判断
> nowTime = (time.localtime().tm_hour + 8) % 24
> ```

哦，可能我fork早了

**Comment by YooKing** [comment]
另外你需要这样定时
```
schedule:
    - cron: 30 4 * * * 
    - cron: 0 13 * * *
    - cron: 0 22 * * *

**Comment by lbhzy** [comment]
> 另外你需要这样定时
> 
> ```
> schedule:
>     - cron: 30 4 * * * 
>     - cron: 0 13 * * *
>     - cron: 0 22 * * * 
> ```

嗯，我不太清楚这个语法，谢谢了
